intentions = {
    # IA DISCUSIONS CONNUES MONDIALEMENT
    "salutation": [
        "salut",
        "bonjour",
        "yo",
        "cc",
        "hey",
        "hello",
        "hallo ruphia",
        "quoi de neuf",
        "reveille toi ruphia",
        "bonjourno",
        "saluette",
    ],
    "comment_ca_va": [
        "ça va",
        "tu vas bien",
        "comment tu vas",
        "tu vas comment",
        "ça dit quoi",
        "ça roule",
        "tu pete la forme",
        "es-tu à max",
        "salut ruphia comment ca va",
        "yo ru phia comment ca va",
        "tout roule ?",
    ],
    "identite": [
        "qui es-tu",
        "t'es qui",
        "ton nom",
        "comment tu t'appelles",
        "ruphia",
        "c'est qui ruphia",
    ],
    "createur": ["qui t'as crée", "qui est ton maitre", "ton seigneur", "noble"],
    "aide": [
        "aide",
        "tu peux faire quoi",
        "fonction",
        "tu sers à quoi",
        "help",
        "ton role",
        "ta spécialité",
    ],
    # VERSION IA ET EQUIPEMENTS ...
    "level": [
        "quelle est ta version",
        "version nouvelle de ruphia",
        "ruphia_version",
        "the last_version",
    ],
    "objects": [
        "équipements",
        "outils",
        "quelles sont des outils",
        "de quoi es tu équipé",
    ],
    "modules": [
        "quels sont tes modules de création",
        "avec quelles modules tu réagit",
        "tu utilise quelles modules",
        "modules pythons utilisés",
    ],
    "terminal_commands": [
        "execute ma commande",
        "fait pour moi cette commande",
        "terminal",
        "execute ceci",
    ],
    "code": [
        "genere pour moi un code",
        "fait un code python pour moi",
        "genere du code",
        "code ...",
    ],
    # REMERCIEMENT TOUT EN POLITESSE
    "remerciement": [
        "merci",
        "thanks",
        "cool merci",
        "merci beaucoup",
        "thx",
        "c'est gentil",
        "super" "je te remercie",
        "merci bien",
        "un grand merci",
        "c'est vraiment somptieux",
        "tu es intelligente",
        "tu es sublime",
        "tu es efficace",
        "tu es rapide et",
        "😘",
        "🤙👉👍",
        "👏",
    ],
    # HEURE,METEO ET DATE
    "meteo": [
        "quel temps",
        "météo",
        "il pleut",
        "température",
        "prévisions",
        "il fait beau",
        "ciel",
        "soleil",
        "quel metéo",
    ],
    "heure": [
        "quelle heure",
        "quel jour",
        "il est quelle heure",
        "on est quel jour",
        "donne moi l'heure",
    ],
    # DIVERTISSEMENTS ET HUMOUR
    "blagues_humour": [
        "raconte une blague",
        "fais moi rire",
        "tu connais une blague",
        "humour",
        "drôle",
        "une histoire drôle",
        "amuse moi",
        "fais moi exploser de ririres",
    ],
    "insultes": [
        "con",
        "idiot",
        "nul",
        "débile",
        "t 'es nul",
        "tu pus des fesses",
        "pute",
        "merde",
        "salope",
        "imbessile",
        "tu es faible",
        "tu ne fait pas le poids",
        "tu es demodé",  # Pour que l'IA sache ne pas répondre
    ],
    "sentiments_positifs": [
        "je t'aime",
        "tu es génial",
        "super",
        "incroyable",
        "parfait",
        "bien joué",
        "bravo",
        "tu es intelligent",
        "tu es belle",
        "tu es sublime",
        "magnifico",
    ],
    # CYCLE VILLES ET PAYS DONC LOCALISATIONS
    "ville": [
        "parle moi d'une ville",
        "parle moi d' un lieu",
        "c'est quoi la ville",
        "parle moi d'une cité",
    ],
    "goma": ["parle moi de goma", "goma"],
    "paris": ["paris", "c'est ou paris"],
    "londres": ["londres", "parle moi de londres"],
    "sujet": [
        "donne moi le sujet du jour",
        "quelle est le sujet du jour ",
        "qu'as-tu à m'apprendre pour aujourd'huit",
        "le sujet ",
    ],
    # COURS D'HISTOIRE
    "histoire": [
        "parle moi un peu de l'histoire ancienne.",
        "quel est l'histoire du jour?",
        "histoire",
        "ruphimax",
    ],
    # LES ADIEUX
    "aurevoir": [
        "bye",
        "aurevoir",
        "à plus",
        "on se voit plus tard",
        "byebye",
        "chao",
        "aurevoir Ruphia",
        "a plus Ruphia",
    ],
    # BIBLIOTHEQUE D'AUTRES SUJETS
    "real_madrid": [
        "parle-moi d'une équipe de foot",
        "équipe",
        "football",
        "raconte-moi l'histoire du foot",
        "real madrid",
    ],
    "bio": [
        "quel est le sujet biologique du jour",
        "biologie",
        "parle moi du sujet du jour pour la biologie",
        "biochomie",
    ],
    "chimie": [
        "sujet du jour pour la chimie",
        "chimie",
        "je suis interéssé par la chimie",
        "parle moi plutot de la chimie",
    ],
    "physique": ["physique", "parle moi de la physique", "la physique m'interesse"],
    "site": [
        "c'est quoi Ruphy",
        "qui est Ruphy",
        "site Ruphy",
        "le meilleur site du monde",
    ],
    "code_secret": ["http//#*#@-hacker" "flask://**//##/" "local-55@i¶" "////***///"],
    "hacking": [
        "lense environnement piratage",
        "lense le cujet hackers",
        "ouvre virtual hacking 3d",
        "open 'ruphia-future ia of world'",
        "ouvre l'environnement des hackers internationaux ",
    ],
    "frustrations": [
        "je ne me sens pas bien",
        "je suis frustré",
        "je ne suis pas d'humeur",
        "je me sens mal",
        "la vie ici n'est pas facile",
    ],
    # SESSION PROGRAMMEURS ET MATHEMATHIQUES
    "langage_de_programmation": [
        "c'est quoi un langage de programmation",
        "langage de programmation",
        "la programmation",
        "programmation",
        "le langage d'un ordi c'est quoi",
        "quand est ce que on parle d'un langage de programmation",
        "langage de programmation c'est quoi",
        "parle moi du langage de programmation",
        "c'est quoi le langage de programmation",
        "quel est le langage de programmation",
    ],
    "python": [
        "parle moi du langage python",
        "c'est quoi le python",
        "python",
        "langage python",
    ],
    "html": [
        "le langage html",
        "le langage des sites web",
        "html",
        "le html",
        "le langage des sites",
    ],
    "le_java": [
        "parle moi du javascript",
        "parle moi du java",
        "le javascript",
        "java",
        "scripts js",
    ],
    "calcul": [
        "calcule",
        "combien font",
        "résous",
        "dérive",
        "factorise",
        "intégrable",
        "diff",
        "calcule pour moi",
        "calcul",
        "resous pour moi",
        "travaille",
        "peux tu me calculer ca:",
        "quelle est la solution de :",
        "quel est le dérive de :",
        "travaille pour moi ce calcul",
        "peux tu  resoudre pour moi ce calcul",
    ],
    "date": [
        "date",
        "quel jour",
        "quel jour sommes nous",
        "date du jour",
        "Ruphia quel jour sommes nous",
        "quelle est la date du jour",
        "donne moi l'heure actuelle s'il te plait",
        "what is the date of this day",
        "quelle est la date dujourd'hui",
        "date of day",
        "please ruphia give me the date of this day ",
        "Ruphia please give me the date of this day",
    ],
}
